### ISSUE TITLE
Issue with hiera since v 7.0.0

### ISSUE THREAD

**Issue by ondrejv2** [voxpupuli/puppet-systemd#458]
Hello,
Since I upgraded to 7.0.0 I seem to have an issue with hiera.
My config:
```
node 'sloetxct003v.adwin.renesas.com' {
  include ::systemd
}
```
```
systemd::manage_units:
  user-.slice:
    unit_entry:
      Description: User session limits
    slice_entry:
      CPUWeight: 2000
      MemoryMax: '17G'
```
In Puppetfile I have:
```
mod 'puppetlabs-stdlib',                    '9.6.0'
mod 'puppet-systemd', 			    '7.0.0'
```
but still I receive compilation error on Puppet run:
```
Info: Using environment 'development'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Resource type not found: Stdlib::CreateResources (file: /etc/puppetlabs/code/environments/development/modules/systemd/manifests/init.pp, line: 205, column: 3) on node sloetxct003v.adwin.renesas.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

I am pretty sure it did not behave like this with the previous version 6.6.0.
Any ideas what could be wrong?

**Comment by traylenator** [comment]
You need to respect the minimum version of puppetlabs-stdlib:

https://github.com/voxpupuli/puppet-systemd/blob/v7.0.0/metadata.json#L12

**Comment by ondrejv2** [comment]
That was it!
Changed version to 9.0.0 which happen to suffice old modules requirement as well as Puppet-systemd module.
Thanks for the quick reply!
